#!/bin/bash

print_help() {
    echo 'Usage: insight [OPTION]'
    echo 'CLI for my personal systems outlined in CONTROL and other projects.'
    echo 'OPTIONS:'
    echo '-h, --help       print this help and exit'
    echo '-d, --diary      create a diary entry interactively'
}

case "$1" in
    '--help'|'-h')
        print_help
        ;;
    '--diary'|'-d')
        shift
        ~/Steel/INSIGHT/diary.py $@
        ;;
    *)
        echo
esac
