#!/bin/sh

no_color=\e[0m
aquamarine=122
aquamarine2=123
aquamarine3=85
aquamarine4=86
aquamarine5=87
beige=194
black=16
black2=232
black3=233
black4=234
blue=21
blue_violet=57
cadet_blue=72
cadet_blue2=73
chartreuse=118
chocolate=166
coral=209
corn_flower_blue=68
corn_flower_blue=69
corn_flower_blue=74
corn_flower_blue=75
corn_silk=230
crimson=161
crimson2=197
cyan=50
cyan2=51
darkblue=18
dark_cyan=25
dark_cyan2=30
dark_cyan3=31
dark_cyan4=35
dark_cyan5=36
darkgoldenrod=130
darkgoldenrod2=136
darkgoldenrod3=142
darkgoldenrod4=172
dark_green=22
dark_grey=109
dark_grey2=139
dark_grey3=145
dark_grey4=247
dark_grey5=248
dark_grey6=249
dark_khaki=143
dark_khaki2=144
dark_khaki3=149
dark_khaki4=179
dark_khaki5=185
dark_magenta=90
dark_magenta2=91
dark_orange=208
dark_red=124
dark_red2=88
dark_sea_green=107
dark_sea_green2=108
darkslategrey=235
dark_slate_grey=236
dark_slate_grey2=237
dark_slate_grey3=238
dark_slate_grey4=239
dark_turquoise=38
dark_turquoise2=43
dark_turquoise3=44
dark_violet=127
dark_violet2=128
dark_violet3=129
dark_violet4=56
dark_violet5=92
dark_violet6=93
deep_pink=198
deep_pink2=199
deep_sky_blue=39
deep_sky_blue2=45
dim_grey=240
dim_grey2=241
dim_grey3=242
dim_grey4=59
dim_grey5=60
dim_grey6=65
dim_grey7=95
dodger_blue=27
dodger_blue2=32
dodger_blue3=33
gainsboro=253
gainsboro2=254
gold=184
gold2=220
goldenrod=178
green=2
green2=28
green3=34
green_yellow=154
green_yellow2=155
grey=101
grey2=102
grey3=243
grey4=244
grey5=245
grey6=8
grey7=96
hot_pink=205
hot_pink2=206
hot_pink3=211
indian_red=131
indian_red2=167
indigo=53
indigo2=54
indigo3=55
khaki=186
khaki4=191
khaki5=192
khaki6=221
khaki7=222
khaki8=227
khaki9=228
lavender=189
lavender_blush=225
lawn_green=112
lawn_green2=76
lawn_green3=82
light_blue=152
light_blue1=153
light_coral=204
light_coral1=210
light_cyan=195
light_green=114
light_green2=119
light_green2=120
light_green4=150
light_green5=83
light_green6=84
light_grey=188
light_grey2=252
light_pink=217
light_salmon=216
light_sea_green=37
light_sky_blue=111
light_sky_blue2=117
light_sky_blue3=81
light_slate_grey=103
light_slate_grey2=246
light_steel_blue=146
light_steel_blue2=147
lime=10
lime2=40
lime3=46
magenta=13
magenta2=164
magenta3=165
magenta4=200
magenta5=201
maroon=1
maroon2=52
medium_aquamarine=115
medium_aquamarine2=78
medium_aquamarine3=79
medium_blue=19
medium_blue2=20
medium_orchid=133
medium_orchid2=134
medium_orchid3=135
medium_purple=104
medium_purple2=140
medium_purple3=141
medium_purple4=98
medium_sea_green=71
medium_sea_green2=77
medium_slate_blue=105
medium_slate_blue2=63
medium_slate_blue3=99
medium_spring_green=42
medium_spring_green2=49
medium_turquoise=80
medium_violet_red=125
medium_violet_red2=126
medium_violet_red3=162
medium_violet_red4=163
misty_rose=224
moccasin=229
navjao_white=223
navy=17
navy2=4
olive=100
olive2=106
olive3=3
olive4=58
olive5=64
olive_drab=70
orange=214
orange_red=202
orchid=170
orchid2=171
orchid3=176
pale_goldenrod=187
pale_goldenrod2=193
pale_green=121
pale_green2=156
pale_green3=157
pale_turquoise=158
pale_turquoise2=159
pale_violet_red=132
pale_violet_red2=168
pale_violet_red3=169
pale_violet_red4=174
pale_violet_red5=175
peru=137
peru2=173
pink=218
plum=183
plum2=219
purple=5
purple2=89
red=160
red2=196
red3=9
rosy_brown=138
royal_blue=26
saddle_brown=94
sandy_brown=215
silver=151
silver2=181
silver3=250
silver4=251
silver5=7
sky_blue=110
sky_blue2=116
slate_blue=61
slate_blue2=62
slate_blue3=97
slate_grey=66
spring_green=41
spring_green=47
spring_green2=48
steel_blue=67
tan=180
teal=23
teal2=24
teal3=29
teal4=6
thistle=182
tomato=203
violet=177
violet2=207
violet3=212
violet4=213
white=231
white_smoke=255
yellow=11
yellow2=190
yellow3=226
yellow_green=113
yellow_green2=148

text() {
	echo "\x1b[38;5;$1m"
}


AQUAMARINE=$(text $aquamarine)
AQUAMARINE2=$(text $aquamarine2)
AQUAMARINE3=$(text $aquamarine3)
AQUAMARINE4=$(text $aquamarine4)
AQUAMARINE5=$(text $aquamarine5)
BEIGE=$(text $beige)
BLACK=$(text $black)
BLACK2=$(text $black2)
BLACK3=$(text $black3)
BLACK4=$(text $black4)
BLUE=$(text $blue)
BLUE_VIOLET=$(text $blue_violet)
CADET_BLUE=$(text $cadet_blue)
CADET_BLUE2=$(text $cadet_blue2)
CHARTREUSE=$(text $chartreuse)
CHOCOLATE=$(text $chocolate)
CORAL=$(text $coral)
CORN_FLOWER_BLUE=$(text $corn_flower_blue)
CORN_FLOWER_BLUE=$(text $corn_flower_blue)
CORN_FLOWER_BLUE=$(text $corn_flower_blue)
CORN_FLOWER_BLUE=$(text $corn_flower_blue)
CORN_SILK=$(text $corn_silk)
CRIMSON=$(text $crimson)
CRIMSON2=$(text $crimson2)
CYAN=$(text $cyan)
CYAN2=$(text $cyan2)
DARKBLUE=$(text $darkblue)
DARK_CYAN=$(text $dark_cyan)
DARK_CYAN2=$(text $dark_cyan2)
DARK_CYAN3=$(text $dark_cyan3)
DARK_CYAN4=$(text $dark_cyan4)
DARK_CYAN5=$(text $dark_cyan5)
DARKGOLDENROD=$(text $darkgoldenrod)
DARKGOLDENROD2=$(text $darkgoldenrod2)
DARKGOLDENROD3=$(text $darkgoldenrod3)
DARKGOLDENROD4=$(text $darkgoldenrod4)
DARK_GREEN=$(text $dark_green)
DARK_GREY=$(text $dark_grey)
DARK_GREY2=$(text $dark_grey2)
DARK_GREY3=$(text $dark_grey3)
DARK_GREY4=$(text $dark_grey4)
DARK_GREY5=$(text $dark_grey5)
DARK_GREY6=$(text $dark_grey6)
DARK_KHAKI=$(text $dark_khaki)
DARK_KHAKI2=$(text $dark_khaki2)
DARK_KHAKI3=$(text $dark_khaki3)
DARK_KHAKI4=$(text $dark_khaki4)
DARK_KHAKI5=$(text $dark_khaki5)
DARK_MAGENTA=$(text $dark_magenta)
DARK_MAGENTA2=$(text $dark_magenta2)
DARK_ORANGE=$(text $dark_orange)
DARK_RED=$(text $dark_red)
DARK_RED2=$(text $dark_red2)
DARK_SEA_GREEN=$(text $dark_sea_green)
DARK_SEA_GREEN2=$(text $dark_sea_green2)
DARKSLATEGREY=$(text $darkslategrey)
DARK_SLATE_GREY=$(text $dark_slate_grey)
DARK_SLATE_GREY2=$(text $dark_slate_grey2)
DARK_SLATE_GREY3=$(text $dark_slate_grey3)
DARK_SLATE_GREY4=$(text $dark_slate_grey4)
DARK_TURQUOISE=$(text $dark_turquoise)
DARK_TURQUOISE2=$(text $dark_turquoise2)
DARK_TURQUOISE3=$(text $dark_turquoise3)
DARK_VIOLET=$(text $dark_violet)
DARK_VIOLET2=$(text $dark_violet2)
DARK_VIOLET3=$(text $dark_violet3)
DARK_VIOLET4=$(text $dark_violet4)
DARK_VIOLET5=$(text $dark_violet5)
DARK_VIOLET6=$(text $dark_violet6)
DEEP_PINK=$(text $deep_pink)
DEEP_PINK2=$(text $deep_pink2)
DEEP_SKY_BLUE=$(text $deep_sky_blue)
DEEP_SKY_BLUE2=$(text $deep_sky_blue2)
DIM_GREY=$(text $dim_grey)
DIM_GREY2=$(text $dim_grey2)
DIM_GREY3=$(text $dim_grey3)
DIM_GREY=$(text $dim_grey)
DIM_GREY5=$(text $dim_grey5)
DIM_GREY6=$(text $dim_grey6)
DIM_GREY7=$(text $dim_grey7)
DODGER_BLUE=$(text $dodger_blue)
DODGER_BLUE2=$(text $dodger_blue2)
DODGER_BLUE3=$(text $dodger_blue3)
GAINSBORO=$(text $gainsboro)
GAINSBORO2=$(text $gainsboro2)
GOLD=$(text $gold)
GOLD2=$(text $gold2)
GOLDENROD=$(text $goldenrod)
GREEN=$(text $green)
GREEN2=$(text $green2)
GREEN3=$(text $green3)
GREEN_YELLOW=$(text $green_yellow)
GREEN_YELLOW2=$(text $green_yellow2)
GREY=$(text $grey)
GREY2=$(text $grey2)
GREY3=$(text $grey3)
GREY4=$(text $grey4)
GREY5=$(text $grey5)
GREY6=$(text $grey6)
GREY7=$(text $grey7)
HOT_PINK=$(text $hot_pink)
HOT_PINK2=$(text $hot_pink2)
HOT_PINK3=$(text $hot_pink3)
INDIAN_RED=$(text $indian_red)
INDIAN_RED2=$(text $indian_red2)
INDIGO=$(text $indigo)
INDIGO2=$(text $indigo2)
INDIGO3=$(text $indigo3)
KHAKI=$(text $khaki)
KHAKI4=$(text $khaki4)
KHAKI5=$(text $khaki5)
KHAKI6=$(text $khaki6)
KHAKI7=$(text $khaki7)
KHAKI8=$(text $khaki8)
KHAKI9=$(text $khaki9)
LAVENDER=$(text $lavender)
LAVENDER_BLUSH=$(text $lavender_blush)
LAWN_GREEN=$(text $lawn_green)
LAWN_GREEN2=$(text $lawn_green2)
LAWN_GREEN3=$(text $lawn_green3)
LIGHT_BLUE=$(text $light_blue)
LIGHT_BLUE1=$(text $light_blue1)
LIGHT_CORAL=$(text $light_coral)
LIGHT_CORAL1=$(text $light_coral1)
LIGHT_CYAN=$(text $light_cyan)
LIGHT_GREEN=$(text $light_green)
LIGHT_GREEN2=$(text $light_green2)
LIGHT_GREEN2=$(text $light_green2)
LIGHT_GREEN4=$(text $light_green4)
LIGHT_GREEN5=$(text $light_green5)
LIGHT_GREEN6=$(text $light_green6)
LIGHT_GREY=$(text $light_grey)
LIGHT_GREY2=$(text $light_grey2)
LIGHT_PINK=$(text $light_pink)
LIGHT_SALMON=$(text $light_salmon)
LIGHT_SEA_GREEN=$(text $light_sea_green)
LIGHT_SKY_BLUE=$(text $light_sky_blue)
LIGHT_SKY_BLUE2=$(text $light_sky_blue2)
LIGHT_SKY_BLUE3=$(text $light_sky_blue3)
LIGHT_SLATE_GREY=$(text $light_slate_grey)
LIGHT_SLATE_GREY2=$(text $light_slate_grey2)
LIGHT_STEEL_BLUE=$(text $light_steel_blue)
LIGHT_STEEL_BLUE2=$(text $light_steel_blue2)
LIME=$(text $lime)
LIME2=$(text $lime2)
LIME3=$(text $lime3)
MAGENTA=$(text $magenta)
MAGENTA2=$(text $magenta2)
MAGENTA3=$(text $magenta3)
MAGENTA4=$(text $magenta4)
MAGENTA5=$(text $magenta5)
MAROON=$(text $maroon)
MAROON2=$(text $maroon2)
MEDIUM_AQUAMARINE=$(text $medium_aquamarine)
MEDIUM_AQUAMARINE2=$(text $medium_aquamarine2)
MEDIUM_AQUAMARINE3=$(text $medium_aquamarine3)
MEDIUM_BLUE=$(text $medium_blue)
MEDIUM_BLUE2=$(text $medium_blue2)
MEDIUM_ORCHID=$(text $medium_orchid)
MEDIUM_ORCHID2=$(text $medium_orchid2)
MEDIUM_ORCHID3=$(text $medium_orchid3)
MEDIUM_PURPLE=$(text $medium_purple)
MEDIUM_PURPLE2=$(text $medium_purple2)
MEDIUM_PURPLE3=$(text $medium_purple3)
MEDIUM_PURPLE4=$(text $medium_purple4)
MEDIUM_SEA_GREEN=$(text $medium_sea_green)
MEDIUM_SEA_GREEN2=$(text $medium_sea_green2)
MEDIUM_SLATE_BLUE=$(text $medium_slate_blue)
MEDIUM_SLATE_BLUE2=$(text $medium_slate_blue2)
MEDIUM_SLATE_BLUE3=$(text $medium_slate_blue3)
MEDIUM_SPRING_GREEN=$(text $medium_spring_green)
MEDIUM_SPRING_GREEN2=$(text $medium_spring_green2)
MEDIUM_TURQUOISE=$(text $medium_turquoise)
MEDIUM_VIOLET_RED=$(text $medium_violet_red)
MEDIUM_VIOLET_RED2=$(text $medium_violet_red2)
MEDIUM_VIOLET_RED3=$(text $medium_violet_red3)
MEDIUM_VIOLET_RED4=$(text $medium_violet_red4)
MISTY_ROSE=$(text $misty_rose)
MOCCASIN=$(text $moccasin)
NAVJAO_WHITE=$(text $navjao_white)
NAVY=$(text $navy)
NAVY2=$(text $navy2)
OLIVE=$(text $olive)
OLIVE2=$(text $olive2)
OLIVE3=$(text $olive3)
OLIVE4=$(text $olive4)
OLIVE5=$(text $olive5)
OLIVE_DRAB=$(text $olive_drab)
ORANGE=$(text $orange)
ORANGE_RED=$(text $orange_red)
ORCHID=$(text $orchid)
ORCHID2=$(text $orchid2)
ORCHID3=$(text $orchid3)
PALE_GOLDENROD=$(text $pale_goldenrod)
PALE_GOLDENROD2=$(text $pale_goldenrod2)
PALE_GREEN=$(text $pale_green)
PALE_GREEN2=$(text $pale_green2)
PALE_GREEN3=$(text $pale_green3)
PALE_TURQUOISE=$(text $pale_turquoise)
PALE_TURQUOISE2=$(text $pale_turquoise2)
PALE_VIOLET_RED=$(text $pale_violet_red)
PALE_VIOLET_RED2=$(text $pale_violet_red2)
PALE_VIOLET_RED3=$(text $pale_violet_red3)
PALE_VIOLET_RED4=$(text $pale_violet_red4)
PALE_VIOLET_RED5=$(text $pale_violet_red5)
PERU=$(text $peru)
PERU2=$(text $peru2)
PINK=$(text $pink)
PLUM=$(text $plum)
PLUM2=$(text $plum2)
PURPLE=$(text $purple)
PURPLE2=$(text $purple2)
RED=$(text $red)
RED2=$(text $red2)
RED3=$(text $red3)
ROSY_BROWN=$(text $rosy_brown)
ROYAL_BLUE=$(text $royal_blue)
SADDLE_BROWN=$(text $saddle_brown)
SANDY_BROWN=$(text $sandy_brown)
SILVER=$(text $silver)
SILVER2=$(text $silver2)
SILVER3=$(text $silver3)
SILVER4=$(text $silver4)
SILVER5=$(text $silver5)
SKY_BLUE=$(text $sky_blue)
SKY_BLUE2=$(text $sky_blue2)
SLATE_BLUE=$(text $slate_blue)
SLATE_BLUE2=$(text $slate_blue2)
SLATE_BLUE3=$(text $slate_blue3)
SLATE_GREY=$(text $slate_grey)
SPRING_GREEN=$(text $spring_green)
SPRING_GREEN=$(text $spring_green)
SPRING_GREEN2=$(text $spring_green2)
STEEL_BLUE=$(text $steel_blue)
TAN=$(text $tan)
TEAL=$(text $teal)
TEAL2=$(text $teal2)
TEAL3=$(text $teal3)
TEAL4=$(text $teal4)
THISTLE=$(text $thistle)
TOMATO=$(text $tomato)
VIOLET=$(text $violet)
VIOLET2=$(text $violet2)
VIOLET3=$(text $violet3)
VIOLET4=$(text $violet4)
WHITE=$(text $white)
WHITE_SMOKE=$(text $white_smoke)
YELLOW=$(text $yellow)
YELLOW2=$(text $yellow2)
YELLOW3=$(text $yellow3)
YELLOW_GREEN=$(text $yellow_green)
YELLOW_GREEN2=$(text $yellow_green2)
NO_COLOR=$(text $no_color)
